### ISSUE TITLE
Some images not displaying

### ISSUE THREAD

**Issue by danarth** [gunar/medium-parser#13]
At the moment, medium-parser uses the `data-src` attribute of `<img>` tags in figures that are in the articles:

https://github.com/gunar/medium-parser/blob/2ca35786cd369fbfc947b2b75a380f00d4c4b400/src/processElement.js#L26

However, I have come aross a few articles that do not use the `data-src` attribute on figure images. For example, [this article](https://blog.lavrton.com/how-to-optimise-rendering-of-a-set-of-elements-in-react-ad01f5b161ae) has a figure with the following HTML:

```html
<img class="graf-image" data-image-id="1*ZnE4yeMaFzd-w_BsA2B-DA.png" data-width="432" data-height="76" src="https://cdn-images-1.medium.com/max/1200/1*ZnE4yeMaFzd-w_BsA2B-DA.png">
```

Because the `data-src` attribute is for some reason not there, medium-parser renders the following markdown:

```markdown
![Time for rendering without optimisation](undefined)
```

This could be fixed by using the `<img>` tag's `src` attribute as a last resort:

```javascript
const img = $('div > img').last();
const src = img.attr('data-src') || img.attr('src');
```

**Comment by gunar** [comment]
Nice work! If you can push a PR I'll review and merge.
