### ISSUE TITLE
Italics parsed incorrectly due to unescaped characters

### ISSUE THREAD

**Issue by danarth** [gunar/medium-parser#14]
In Dan Abramov's [famous article](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) on Container and Presentational components, which we actually use as the mock for testing this library, he uses lots of italics as well as an asterisk (\*) in his opening paragraph.

It would seem that medium-parser does not escape asterisks (\*) as it parses, which means that the italics gets confused in the resulting markdown. Here is the example I meant:

**Expected:**
> I call them *Container* and *Presentational* components\* but I also heard *Fat* and *Skinny*, *Smart*  and *Dumb*, *Stateful* and *Pure*, *Screens* and *Components*, etc. These all are not *exactly* the same, but the core idea is similar.

**Actual:**
> I call them \*Container *and* Presentational *components* but I also heard *Fat* and *Skinny*, *Smart* and *Dumb*, *Stateful* and *Pure*, *Screens* and *Components*, etc. These all are not *exactly* the same, but the core idea is similar.

I am not sure if there are any other characters we should consider escaping in markdown using the \\ character!

**Comment by gunar** [comment]
Nice catch! I guess we should escape [all of these](https://duckduckgo.com/?q=markdown+characters&ia=answer&iax=1).

**Comment by danarth** [comment]
@gunar Thanks for the list - adding this to my `next` branch now 👍

**Comment by danarth** [comment]
### Update

It turns out that this is not entirely an issue with the way we escape markdown characters. It is also to do with the way that Medium generates some HTML. In particular, it's the way that trailing spaces left inside HTML tags confuse the generated markdown. From my example at the top, consider the HTML generated by medium (I have removed class names and other unnecessary attributes for readability):

```html
<p>
  You’ll find your components much easier to reuse and reason about if you <strong>divide them into two categories.</strong> I call them <em>Container </em>and<em> Presentational </em>components* but I also heard <em>Fat</em> and <em>Skinny</em>, <em>Smart</em> and <em>Dumb,</em> <em>Stateful</em> and <em>Pure</em>, <em>Screens</em> and <em>Components</em>, etc. These all are not <em>exactly</em> the same, but the core idea is similar.
</p>
```

This is where it gets interesting:

```html
I call them <em>Container </em>and<em> Presentational </em>components*
```

As you can see, Medium has added strange whitespace to the insides of HTML tags, rendering the correct markdown as so:

```md
I call them *Container *and* Presentational *components\*
```
But the placement of the asterisks confuses most markdown engines, and we are left with the result:

> I call them *Container *and* Presentational *components\*

The solution to this problem would be to remove leading and trailing whitespace from the insides of tags but then adding the exact same amount of whitespace outside the tags to preserve the style and formatting that the original author intends.

I am working on this solution now and early signs show that it works!
