### ISSUE TITLE
Transpiled code being stored on GitHub

### ISSUE THREAD

**Issue by Jameskmonger** [gunar/medium-parser#2]
Is there any reason for the transpiled code being stored on GitHub? It's generated from the `src` folder (as far as I can tell), and is distributed through [npm](https://www.npmjs.com/package/medium-parser), so I'm not sure there's a need to keep it under version control. This would reduce the size of the repository for anyone interested in contributing.

**Comment by gunar** [comment]
Done. Thank you very much for the tip!

I wish I could add `/lib` to `.gitignore`, but then npm would ignore that directory too.
